<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'ID' => '',
    'Location Currencies Currency Id' => 'Валюта',
    'Location Currencies Location Id' => 'Локация',
    'Location ID' => 'Локация',
    'TimeZone' => 'Временная зона',
    'Create Location' => 'Создать новое местоположение',
    'Currency Fmt' => 'Формат',
    'Currency Full Name' => 'Полное обозначение',
    'Currency Iso Code' => 'Код валюты по стандарту ISO 4217',
    'Currency Name' => 'Краткое обозначение',
    'Inherit from parent' => 'Наследовать от вышестоящего',
    'Linked' => 'Есть связь',
    'Location' => 'Местоположение',
    'Location Additions' => 'Дополнительные свойства',
    'Location Code' => 'Литерный код',
    'Location Currency' => 'Валюта',
    'Location Name' => 'Наименование',
    'Location Properties' => 'Основные свойства',
    'Location Timezone' => 'Часовой пояс',
    'Location Type' => 'Тип',
    'Not linked' => 'Нет связи',
    'Property' => 'Свойство',
    'Property Own Value' => 'Собственное значение',
    'Property Parent Value' => 'Значение по вышестоящему',
    'Save Location Links' => 'Сохранить изменения связей',
    'Some of these locations do not exist.' => 'Некоторые (или все) из переданных мест не существуют в БД.',
    'This currency does not exist.' => 'Такая валюта не существует.',
    'Update' => 'Редактировать',
    'Update Location Lower' => 'Изменить состав нижестоящих мест',
    'Update Location Upper' => 'Изменить состав вышестоящих мест',
];
